src/main/java/envisionari/beans/UsersBean.java
package envisionari.beans;

import envisionari.models.Swsusers;

import javax.ejb.Stateless;
import javax.faces.bean.ManagedBean;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import java.io.Serializable;
import java.util.List;

import org.apache.log4j.Logger;
import org.json.JSONObject;

@Stateless(name = "UsersEJB")
@ManagedBean
public class UsersBean implements Serializable {

    @PersistenceContext(unitName="kazsw-persistence-unit")
    private EntityManager em;
    private final static Logger LOG = Logger.getLogger(UsersBean.class);


    public JSONObject createUser(Swsusers user) {
        LOG.info(String.format("Creating user '%s'", user.getUsername()));

        JSONObject result = new JSONObject();
        if (user.getUsername().isEmpty()) {
            result.put("error", "Required field 'name' missing");
        }
        else {
            result.put("name", user.getUsername());

            if (!this.exists(Swsusers.class, "username", user.getUsername())) {
                this.em.persist(user);
            }
            else {
                result.put("error", "Unique username required");
                LOG.error(String.format("Unique username required '%s'", user.getUsername()));
            }
        }

        return result;
    }

    public JSONObject deleteUser(String name) {
        JSONObject result = new JSONObject();
        result.put("name", name);
        this.deleteUser(em.find(Swsusers.class, name));

        return result;
    }

    public void deleteUser(Swsusers user) {
        LOG.info(String.format("Removing user '%s'",user.getUsername()));
        this.em.remove(this.em.contains(user) ? user : this.em.merge(user));
    }

    public List<Swsusers> getUsers() {
        final CriteriaQuery<Swsusers> criteria = em.getCriteriaBuilder().createQuery(Swsusers.class);
        criteria.select(criteria.from(Swsusers.class));

        return this.em.createQuery(criteria).getResultList();
    }

    private boolean exists(String name) {
        final String query = "select count(e) from Swsusers e where username='"+name+"'";
        // you will always get a single result
        Long count = (Long) this.em.createQuery( query ).getSingleResult();
        return count.equals(0L);
    }

    private <E> boolean exists(final Class<E> entityClass, final String property, final String key) {
        final CriteriaBuilder cb = this.em.getCriteriaBuilder();

        final CriteriaQuery<Long> cq = cb.createQuery(Long.class);
        final Root<E> from = cq.from(entityClass);

        cq.select(cb.count(from));
        cq.where(cb.equal(from.get(property), key));

        final TypedQuery<Long> tq = this.em.createQuery(cq);
        return tq.getSingleResult() > 0;
    }

}

src/main/java/envisionari/models/Swsuserroles.java
package envisionari.models;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Swsuserroles {
    private String username;
    private String role;

    @Id
    @Column(name = "USERNAME")
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Basic
    @Column(name = "ROLE")
    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Swsuserroles that = (Swsuserroles) o;

        if (this.username != null ? !this.username.equals(that.username) : that.username != null)
            return false;
        if (this.role != null ? !this.role.equals(that.role) : that.role != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = this.username != null ? this.username.hashCode() : 0;
        result = 31 * result + (this.role != null ? this.role.hashCode() : 0);
        return result;
    }
}

src/main/java/envisionari/models/Swsusers.java
package envisionari.models;

import javax.persistence.*;

@Entity
public class Swsusers {

    private Long id;
    private String username;
    private String passwd;

    public Swsusers() {
    }

    public Swsusers(Long id, String name, String password) {
        this.id = id;
        this.username = name;
        this.passwd = password;
    }

    @Basic
    @Column(name = "ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Id
    @Column(name = "USERNAME")
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Basic
    @Column(name = "PASSWD")
    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Swsusers swsusers = (Swsusers) o;

        if (this.id != null ? !id.equals(swsusers.id) : swsusers.id != null) return false;
        if (this.username != null ? !this.username.equals(swsusers.username) : swsusers.username != null)
            return false;
        if (this.passwd != null ? !this.passwd.equals(swsusers.passwd) : swsusers.passwd != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = this.id != null ? this.id.hashCode() : 0;
        result = 31 * result + (this.username != null ? this.username.hashCode() : 0);
        result = 31 * result + (this.passwd != null ? this.passwd.hashCode() : 0);
        return result;
    }
}

src/main/java/envisionari/controllers/UsersController.java
package envisionari.controllers;

import envisionari.beans.UsersBean;
import envisionari.models.Swsusers;
import org.json.JSONObject;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import java.util.List;

@RequestScoped
@ManagedBean
public class UsersController {

    @EJB
    private UsersBean users;
    // Session parameters
    private Long id;
    private String username;
    private String password;
    private String result;

    @PostConstruct
    public void init() {
    }

    public void add() {
        Swsusers user = new Swsusers(this.id, this.username, this.password);
        JSONObject result = this.users.createUser(user);
        if (result.has("error")) {
            this.result = result.getString("error");
        }
        else {
            this.result = String.format("User '%s' created", this.username);
        }
    }

    public void remove(Swsusers user) {
        this.users.deleteUser(user);
        this.result = String.format("User '%s' removed", user.getUsername());
    }

    public List<Swsusers> getList() {
        return this.users.getUsers();
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}

src/main/webapp/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf">

<h:head>
    <title>Envisionari user form</title>

    <h:outputScript name="js/jquery-3.3.1.min.js" position="first"/>
    <h:outputScript name="js/user-form.js" position="last"/>
    <h:outputStylesheet name="css/user-form.css" position="last"/>
</h:head>
<h:body>

    <b:row class="header text-center">
        <span>
            <b:image class="logo" value="#{resource['img/logo-black.png']}"/>
        </span>
        <span class="bold">USR</span>
        <span class="light">ENVISIONARI</span>
    </b:row>

    <b:row class="full-container">
        <b:container>
            <b:row>
                <h:form id="users">
                    <b:dataTable class="users" value="#{usersController.list}" var="user" border="false" paginated='false' searching='false'>
                        <b:dataTableColumn header-style-class="col-md-1" value="#{user.id}" />
                        <b:dataTableColumn header-style-class="col-md-4" value="#{user.username}" />
                        <b:dataTableColumn header-style-class="col-md-6" value="#{user.passwd}" label="Password"/>
                        <b:dataTableColumn header-style-class="col-md-1" style-class="text-right action" label="Action">
                            <b:commandButton look="inverse" class="remove" value="Del" ajax="true" action="#{usersController.remove(user)}" update="@Form user-add" />
                        </b:dataTableColumn>
                    </b:dataTable>
                </h:form>
            </b:row>

            <!--<b:row>-->
            <!--NO AJAX-->
            <!--<form method="post" action="users-add" accept-charset="UTF-8">-->
            <!--<label for="id">ID</label>-->
            <!--<input id="id" name="id"/>-->
            <!--<label for="name">Name</label>-->
            <!--<input id="name" name="name"/>-->
            <!--<label for="password">Password</label>-->
            <!--<input id="password" name="password"/>-->
            <!--<input type="submit"/>-->
            <!--</form>-->
            <!--</b:row>-->

            <b:row>
                <h:form id="user-add" inline="true">
                    <b:row>
                        <b:column span="1">
                            <b:inputText label="Id" value="#{usersController.id}" required="true" />
                        </b:column>
                        <b:column span="4">
                            <b:inputText label="Username" value="#{usersController.username}" required="true" />
                        </b:column>
                        <b:column span="6" class="password">
                            <b:inputText label="Password" value="#{usersController.password}" required="true" />
                        </b:column>
                        <b:column span="1" class="text-right action-add">
                            <b:commandButton class="add" look="inverse" ajax="true" value="Add" action="#{usersController.add}" update="@Form users" />
                        </b:column>
                    </b:row>
                    <b:row class="status">
                        <h:outputText value="#{usersController.result}" />
                    </b:row>
                </h:form>
            </b:row>
        </b:container>
    </b:row>
</h:body>
</html>